# -*- coding: utf-8 -*-
"""text_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHhNKwCL72n0PPRtsAse7g80WQAQrrte
"""

import pandas as pd











# from transformers import pipeline

# classifier = pipeline("zero-shot-classification")



from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
# Load a model that is good at capturing context
model_name = "roberta-large-mnli"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
# Create a classification pipeline
classifier = pipeline("zero-shot-classification", model=model, tokenizer=tokenizer)

text = "I feel anxious a little bit."
labels = ["never", "sometimes", "often", "always", "rarely"]

# Provide additional context in the prompt
prompt = f"Based on the statement: '{text}', how often does the person get anxious?"
result = classifier(prompt, candidate_labels=labels)
print(result['labels'][0])

